[package]
name = "indexer_v2"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
tokio = { version = "1.38.0", features = ["full"]}
sui_types = { git = "https://github.com/mystenlabs/sui", package = "sui-types"}
sui_sdk = { git = "https://github.com/mystenlabs/sui", package = "sui-sdk"}
move_core_types = { git = "https://github.com/mystenlabs/sui", package = "move-core-types"}
sui_package_resolver = { git = "https://github.com/mystenlabs/sui", package = "sui-package-resolver"}
sui_data_ingestion_core = { git = "https://github.com/mystenlabs/sui", package = "sui-data-ingestion-core"}
move_binary_format = { git = "https://github.com/mystenlabs/sui", package = "move-binary-format"}
prometheus = "0.13.3"
anyhow = "1.0.86"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
serde_with = "3.8"
chrono = "0.4.40"
bcs = "0.1.6"
dotenv = "0.15.0"
tokio-postgres = "0.7.13"
ref-cast = "1.0.24"
proptest = "1.6.0"
redis = { version = "0.30.0", features = ["tokio-comp"] }
futures = "0.3.31"
uuid = { version = "1.16.0", features = ["v4"] }
axum = "0.7.9"
reqwest = "0.12.15"
async-scoped = { version = "0.9.0", features = ["use-tokio"] }

# [[bin]]
# name = "worker"
# path = "src/worker.rs"

# [[bin]]
# name = "remote_reader"
# path = "remote_reader.rs"

